version: '3.7'

services:
  bstfw.r:
    build:
      context: .
      dockerfile: ./docker/r.Dockerfile
    working_dir: /var/www/html
    tty: true
    volumes:
      - ./rscript:/var/www/html
    privileged: true